name: ci
on: [push, pull_request]
jobs:
  build-MacOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: git clone https://github.com/BlockchainCommons/bc-crypto-base.git && cd bc-crypto-base && ./configure && make && sudo make install
    - run: ./configure
    - run: make check
    - run: sudo make install
    - run: make distcheck && make distclean

  build-Linux:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - run: git clone https://github.com/BlockchainCommons/bc-crypto-base.git && cd bc-crypto-base && ./configure && make && sudo make install
    - run: ./configure && make check
    - run: sudo make install
    - run: make distcheck && make distclean

